# Generated by Django 5.0 on 2024-10-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../avatar-default_lxccrh', upload_to='images/syncora-profile-images/'),
        ),
    ]
