# Generated by Django 5.0 on 2024-10-07 13:00

import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('category', models.CharField(choices=[('WORK', 'Work'), ('SOC', 'Social'), ('FAM', 'Family'), ('APP', 'Appointment'), ('EDU', 'Education'), ('TRAVEL', 'Travel')], max_length=30)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
