# Generated by Django 5.0 on 2024-10-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('due_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], max_length=10)),
                ('category', models.CharField(choices=[('WORK', 'Work'), ('PER', 'Personal'), ('HOME', 'Home'), ('HEALTH', 'Health'), ('FIN', 'Finance'), ('FAM', 'Family'), ('SOC', 'Social'), ('EDU', 'Learning')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='profiles.profile')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
